In [1]:
import pandas as pd

# Load dataset for Level 3 practice
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

#### Part 1: Basic Descriptive Statistics & Measures

In [2]:
#1 Calculate the overall mean, median, standard deviation, and variance of the 'Fare' column.

df.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [5]:
print(f"Mean: {df['Fare'].mean()}")
print(f"Median: {df['Fare'].median()}")

Mean: 32.204207968574636
Median: 14.4542

In [7]:
df['Fare'].describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

In [8]:
#2 Find the 25th, 50th, and 75th percentiles (quantiles) for the 'Age' column using .quantile().

df['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [9]:
#3 Display summary statistics for all categorical (non-numeric) columns using df.describe(include='object').

df.describe(include='object')

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [12]:
#4 Determine the skewness and kurtosis of the 'Fare' distribution using .skew() and .kurt().

print(f"Skew: {df['Fare'].skew()}")
print(f"Kurt: {df['Fare'].kurt()}")

Skew: 4.787316519674893
Kurt: 33.39814088089868

In [15]:
#5 Find the minimum and maximum 'Age' values using .min() and .max(), and identify the index of the oldest passenger using .idxmax().

print(f"Min Age {df['Age'].min()}")
print(f"Max Age {df['Age'].max()}")

print(f"Index of oldest passenger: {df['Age'].idxmax()}")

Min Age 0.42
Max Age 80.0
Index of oldest passenger: 630

#### Part 2: Distribution & Frequency Analysis (value_counts())

In [16]:
#1 Count the total number of passengers by passenger class ('Pclass').

df.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [17]:
df.value_counts('Pclass')

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [21]:
#2Calculate the relative proportion (percentage) of male vs. female passengers using value_counts(normalize=True).

df.value_counts('Sex')*100/len(df)

Sex
male      64.758698
female    35.241302
Name: count, dtype: float64

In [23]:
df.value_counts('Sex',normalize=True)*100

Sex
male      64.758698
female    35.241302
Name: proportion, dtype: float64

In [25]:
#3 Count the number of passengers per boarding port ('Embarked'), including missing (NaN) values in the count.

df.value_counts('Embarked').count()

3