In [1]:
import pandas as pd
import numpy as np

In [7]:
import kagglehub
import os

path = kagglehub.dataset_download(
    "lakshmi25npathi/imdb-dataset-of-50k-movie-reviews"
)

# Display the downloaded files
print(os.listdir(path))

Downloading to C:\Users\RonitJadhav\.cache\kagglehub\datasets\lakshmi25npathi\imdb-dataset-of-50k-movie-reviews\1.archive...

100%|██████████| 25.7M/25.7M [00:08<00:00, 3.22MB/s]

Extracting files...

['IMDB Dataset.csv']

In [8]:
print(os.listdir(path))

['IMDB Dataset.csv']

In [9]:
# Load the dataset
file_path = os.path.join(path, "IMDB Dataset.csv")

df = pd.read_csv(file_path, encoding="latin-1")

# Display the first 5 records
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [10]:
df.shape

(50000, 2)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [15]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [16]:
df.duplicated().sum()

418

In [19]:
df = df.drop_duplicates()

df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[49582 rows x 2 columns]

#### Data Cleaning

In [22]:
df['review'] = df['review'].str.lower()

In [24]:
# Removing white spaces 

df['review'] = df['review'].str.strip()

In [25]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [26]:
import re

def remove_html(data):
    data = re.sub(r'<.*?>','',data)
    return data

In [ ]:
# Removing HTML Tag's

df['review'].apply(remove_html)

In [27]:
# Remove HTML Tag's using replace 

df['review'] = df['review'].str.replace('<.*?>','')

In [28]:
# Removing URL'

def remove_url(data):
    data = re.sub(r"https?://\S+|www\.\S+",'',data)
    return data

In [30]:
df['review'] = df['review'].apply(remove_url)