In [62]:
import pandas as pd 
import numpy as np

In [63]:
movies = pd.read_csv('imdb-top-1000.csv')

In [3]:
movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [30]:
#Find the Top 3 Generes by Earnings

genre = movies.groupby('Genre')['Gross'].sum().sort_values(ascending=False)

In [31]:
genre.head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [33]:
# Find the Genre with Highest IMBD Ratings 

highest_IMDB_rating = movies.groupby('Genre')['IMDB_Rating'].max().sort_values(ascending=False).head(3)

In [34]:
highest_IMDB_rating

Genre
Drama     9.3
Crime     9.2
Action    9.0
Name: IMDB_Rating, dtype: float64

In [56]:
# Find the Genre with Highest Average IMDB Ratings

movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [37]:
#Find the Highest Rated Movie in each Genre

highest_rated = movies.groupby('Genre')['IMDB_Rating'].max().sort_values(ascending=False)

In [38]:
highest_rated

Genre
Drama        9.3
Crime        9.2
Action       9.0
Biography    8.9
Western      8.8
Adventure    8.6
Animation    8.6
Comedy       8.6
Horror       8.5
Mystery      8.4
Fantasy      8.1
Film-Noir    8.1
Family       7.8
Thriller     7.8
Name: IMDB_Rating, dtype: float64

In [58]:
#Find the Director with the most popularity

movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [61]:
# Find the Number of movies Done by Each Actors 

movies.groupby('Star1')['Series_Title'].count().sort_values(ascending=False).head(5)

Star1
Tom Hanks            12
Robert De Niro       11
Clint Eastwood       10
Al Pacino            10
Leonardo DiCaprio     9
Name: Series_Title, dtype: int64

#### Group By Attributes and Methods

In [65]:
len(movies.groupby('Genre'))

14

In [66]:
# How to check each group as How much of rows in it 

movies.groupby('Genre').size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [67]:
movies.groupby('Genre').get_group('Horror')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
271,The Thing,1982,109,Horror,8.1,John Carpenter,Kurt Russell,371271,13782838.0,57.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
707,The Innocents,1961,100,Horror,7.8,Jack Clayton,Deborah Kerr,27007,2616000.0,88.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
844,Halloween,1978,91,Horror,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0
876,The Invisible Man,1933,71,Horror,7.7,James Whale,Claude Rains,30683,298791505.0,87.0
932,Saw,2004,103,Horror,7.6,James Wan,Cary Elwes,379020,56000369.0,46.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0

In [81]:
# Applying the Different Aggregating Function on various numerics columns present in our groupby 

genre = movies.groupby('Genre')

# Applying different agg function to different different columns

genre.agg(
    {
        'Runtime':'mean',
        'IMDB_Rating':'mean',
        'No_of_Votes':'sum',
        'Gross' :'sum',
        'Metascore':'mean'
    }
)

              Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419     72282412  3.263226e+10  73.419580
Adventure  134.111111     7.937500     22576163  9.496922e+09  78.437500
Animation   99.585366     7.930488     21978630  1.463147e+10  81.093333
Biography  136.022727     7.938636     24006844  8.276358e+09  76.240506
Comedy     112.129032     7.901290     27620327  1.566387e+10  78.720000
Crime      126.392523     8.016822     33533615  8.452632e+09  77.080460
Drama      124.737024     7.957439     61367304  3.540997e+10  79.701245
Family     107.500000     7.800000       551221  4.391106e+08  79.000000
Fantasy     85.000000     8.000000       146222  7.827267e+08        NaN
Film-Noir  104.000000     7.966667       367215  1.259105e+08  95.666667
Horror     102.090909     7.909091      3742556  1.034649e+09  80.000000
Mystery    119.083333     7.975000      4203004  1.256417e+09  79.125000
Thriller   108.000000     7.800000        27733  1.755074e+07  81.000000
Western    148.250000     8.350000      1289665  5.822151e+07  78.250000

In [ ]:
#Find the Number of movies Starting with A in each Genre

movies.groupby('Genre')