In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("PromptCloudHQ/imdb-data")

print("Path to dataset files:", path)

Downloading to C:\Users\RonitJadhav\.cache\kagglehub\datasets\PromptCloudHQ\imdb-data\1.archive...

100%|██████████| 134k/134k [00:00<00:00, 229kB/s]

Extracting files...

Path to dataset files: C:\Users\RonitJadhav\.cache\kagglehub\datasets\PromptCloudHQ\imdb-data\versions\1

In [2]:
import os
import kagglehub
import pandas as pd

In [4]:
files = os.listdir(path)

csv_file = [file for file in files if file.endswith('.csv')][0]

csv_file_path = os.path.join(path, csv_file)

df = pd.read_csv(csv_file_path)

df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [5]:
# Display Title of The Movie Having Runtime Greater Than or equal to 180 Minute

df.head(1)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0

In [7]:
df[df['Runtime (Minutes)'] >= 180]['Title']

82     The Wolf of Wall Street
88           The Hateful Eight
311             La vie d'Adèle
828                 Grindhouse
965              Inland Empire
Name: Title, dtype: object

In [16]:
# In Which Year There Was The Highest Average Voting?

df.head(1)

df.sort_values('Votes',ascending=False)[['Year','Votes']].head(5)

     Year    Votes
54   2008  1791916
80   2010  1583625
124  2012  1222645
36   2014  1047747
76   2012  1045588