In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("PromptCloudHQ/imdb-data")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\RonitJadhav\.cache\kagglehub\datasets\PromptCloudHQ\imdb-data\versions\1

In [2]:
import os
import kagglehub
import pandas as pd

In [3]:
files = os.listdir(path)

csv_file = [file for file in files if file.endswith('.csv')][0]

csv_file_path = os.path.join(path, csv_file)

df = pd.read_csv(csv_file_path)

df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

#### Display Top 10 Rows of The Dataset

In [7]:
df.head(10)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
5,6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
6,7,La La Land,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
7,8,Mindhorn,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,NaN,71.0
8,9,The Lost City of Z,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0
9,10,Passengers,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0

#### Find Shape of Our Dataset (Number of Rows And Number of Columns)

In [10]:
df.shape

(1000, 12)

#### Information about the dataset

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB

#### Check Missing Values In The Dataset

In [12]:
df.isna().sum()

Rank                    0
Title                   0
Genre                   0
Description             0
Director                0
Actors                  0
Year                    0
Runtime (Minutes)       0
Rating                  0
Votes                   0
Revenue (Millions)    128
Metascore              64
dtype: int64

#### Drop All The Missing Values

In [13]:
df.dropna(inplace=True)

In [14]:
df.isna().sum()

Rank                  0
Title                 0
Genre                 0
Description           0
Director              0
Actors                0
Year                  0
Runtime (Minutes)     0
Rating                0
Votes                 0
Revenue (Millions)    0
Metascore             0
dtype: int64

#### Display Title of The Movie Having Runtime Greater Than or equal to 180 Minute

In [17]:

df[df['Runtime (Minutes)'] >= 180]['Title']

82     The Wolf of Wall Street
88           The Hateful Eight
311             La vie d'Adèle
Name: Title, dtype: object

#### In Which Year There Was The Highest Average Voting?

In [22]:
average_voting_by_year = df.groupby('Year')['Votes'].mean()
year_with_highest_average_voting = average_voting_by_year.idxmax()

print("Year with the highest average voting:", year_with_highest_average_voting)
print("Average voting in that year:", average_voting_by_year[year_with_highest_average_voting])

Year with the highest average voting: 2012
Average voting in that year: 290861.48387096776

#### In Which Year There Was The Highest Average Revenue?

In [32]:
avg_revenue_year = df.groupby('Year')['Revenue (Millions)'].mean()

avg_revenue_year.sort_values(ascending=False).head(3)

Year
2009    115.742000
2012    110.103065
2010    105.081579
Name: Revenue (Millions), dtype: float64

#### Find The Average Rating For Each Director

In [39]:
avg_director_rating = df.groupby('Director')['Rating'].mean().sort_values(ascending=False)
avg_director_rating

Director
Christopher Nolan                   8.68
Olivier Nakache                     8.60
Makoto Shinkai                      8.60
Florian Henckel von Donnersmarck    8.50
Aamir Khan                          8.50
                                    ...
Sam Taylor-Johnson                  4.10
Joey Curtis                         4.00
George Nolfi                        3.90
James Wong                          2.70
Jason Friedberg                     1.90
Name: Rating, Length: 524, dtype: float64

#### Display Top 10 Lengthy Movies Title and Runtime

In [45]:
df.groupby('Title')['Runtime (Minutes)'].max().sort_values(ascending=False).head(10)

Title
The Hateful Eight                           187
The Wolf of Wall Street                     180
La vie d'Adèle                              180
Cloud Atlas                                 172
3 Idiots                                    170
Interstellar                                169
Pirates of the Caribbean: At World's End    169
The Hobbit: An Unexpected Journey           169
The Curious Case of Benjamin Button         166
Django Unchained                            165
Name: Runtime (Minutes), dtype: int64

#### Display Number of Movies Per Year

In [54]:

df['Year'].value_counts().sort_index().rename('Number of Movies')

Year
2006     41
2007     44
2008     48
2009     45
2010     57
2011     57
2012     62
2013     84
2014     93
2015    109
2016    198
Name: Number of Movies, dtype: int64

#### Find Most Popular Movie Title (Highest Revenue)

In [64]:
df['Revenue (Millions)'].sort_values(ascending=False).head(5)

50    936.63
87    760.51
85    652.18
76    623.28
54    533.32
Name: Revenue (Millions), dtype: float64

In [58]:
# Find the movie with the highest recorded revenue.
highest_revenue_movie = df.loc[df["Revenue (Millions)"].idxmax()]
print(f"Title: {highest_revenue_movie['Title']}")
print(f"Revenue: ${highest_revenue_movie['Revenue (Millions)']:,.2f} million")

Title: Star Wars: Episode VII - The Force Awakens
Revenue: $936.63 million

In [68]:
df.loc[df["Revenue (Millions)"].idxmax()]

Rank                                                                 51
Title                        Star Wars: Episode VII - The Force Awakens
Genre                                          Action,Adventure,Fantasy
Description           Three decades after the defeat of the Galactic...
Director                                                    J.J. Abrams
Actors                Daisy Ridley, John Boyega, Oscar Isaac, Domhna...
Year                                                               2015
Runtime (Minutes)                                                   136
Rating                                                              8.1
Votes                                                            661608
Revenue (Millions)                                               936.63
Metascore                                                          81.0
Name: 50, dtype: object

#### Display Top 10 Highest Rated Movie Titles And its Directors

In [85]:
df.sort_values(by='Rating', ascending=False).head(10)[['Title','Director','Rating']]

                     Title                          Director  Rating
54         The Dark Knight                 Christopher Nolan     9.0
80               Inception                 Christopher Nolan     8.8
36            Interstellar                 Christopher Nolan     8.6
249       The Intouchables                   Olivier Nakache     8.6
96           Kimi no na wa                    Makoto Shinkai     8.6
124  The Dark Knight Rises                 Christopher Nolan     8.5
991       Taare Zameen Par                        Aamir Khan     8.5
133               Whiplash                   Damien Chazelle     8.5
99            The Departed                   Martin Scorsese     8.5
476    The Lives of Others  Florian Henckel von Donnersmarck     8.5

In [74]:
highest_rated_movie =  df.loc[df['Title'].idxmax()]

print(f"Title: {highest_rated_movie['Title']}")
print(f"Director: {highest_rated_movie['Director']}")

Title: Zootopia
Director: Byron Howard

#### Display Top 10 Highest Revenue Movie Titles

In [89]:
df.sort_values(by='Revenue (Millions)',ascending=False).head(10)[['Title','Revenue (Millions)']]

                                          Title  Revenue (Millions)
50   Star Wars: Episode VII - The Force Awakens              936.63
87                                       Avatar              760.51
85                               Jurassic World              652.18
76                                 The Avengers              623.28
54                              The Dark Knight              533.32
12                                    Rogue One              532.17
119                                Finding Dory              486.29
94                      Avengers: Age of Ultron              458.99
124                       The Dark Knight Rises              448.13
578             The Hunger Games: Catching Fire              424.65

#### Find Average Rating of Movies Year Wise

In [91]:
df.groupby('Year')['Rating'].mean().sort_index().rename("Average Rating")

Year
2006    7.143902
2007    7.140909
2008    6.708333
2009    6.911111
2010    6.894737
2011    6.945614
2012    6.933871
2013    6.832143
2014    6.822581
2015    6.674312
2016    6.644444
Name: Average Rating, dtype: float64

#### Does Rating Affect The Revenue?

In [86]:
df.head(1)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0

#### How Many Films of Each Genre Were Made?

In [94]:
df['Genre'].value_counts().head(5)

Genre
Action,Adventure,Sci-Fi    50
Comedy,Drama,Romance       30
Drama                      29
Drama,Romance              27
Comedy                     26
Name: count, dtype: int64

In [95]:
# Count each genre occurrence; movies with multiple genres count once in each genre.
df["Genre"].str.split("|").explode().value_counts()

Genre
Action,Adventure,Sci-Fi    50
Comedy,Drama,Romance       30
Drama                      29
Drama,Romance              27
Comedy                     26
                           ..
Adventure,Drama,History     1
Action,Crime,Fantasy        1
Comedy,Mystery              1
Adventure,Comedy,Horror     1
Comedy,Family,Fantasy       1
Name: count, Length: 189, dtype: int64