In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("gustavomodelli/forest-fires-in-brazil")

print("Path to dataset files:", path)

Downloading to C:\Users\RonitJadhav\.cache\kagglehub\datasets\gustavomodelli\forest-fires-in-brazil\1.archive...

100%|██████████| 31.1k/31.1k [00:00<00:00, 5.69MB/s]

Extracting files...
Path to dataset files: C:\Users\RonitJadhav\.cache\kagglehub\datasets\gustavomodelli\forest-fires-in-brazil\versions\1

In [6]:
import os
df = pd.read_csv(os.path.join(path, "amazon.csv"), encoding="latin1")

#### 1. Display Top 5 Rows of The Dataset

In [7]:
df.head(5)

   year state    month  number        date
0  1998  Acre  Janeiro     0.0  1998-01-01
1  1999  Acre  Janeiro     0.0  1999-01-01
2  2000  Acre  Janeiro     0.0  2000-01-01
3  2001  Acre  Janeiro     0.0  2001-01-01
4  2002  Acre  Janeiro     0.0  2002-01-01

#### 2. Check Last 5 Rows

In [8]:
df.tail(5)

      year      state     month  number        date
6449  2012  Tocantins  Dezembro   128.0  2012-01-01
6450  2013  Tocantins  Dezembro    85.0  2013-01-01
6451  2014  Tocantins  Dezembro   223.0  2014-01-01
6452  2015  Tocantins  Dezembro   373.0  2015-01-01
6453  2016  Tocantins  Dezembro   119.0  2016-01-01

#### 3. Find Shape of Our Dataset (Number of Rows And Number of Columns)

In [10]:
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 6454
Columns: 5

#### 4. Getting Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column And Memory Requirement

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    6454 non-null   int64
 1   state   6454 non-null   object
 2   month   6454 non-null   object
 3   number  6454 non-null   float64
 4   date    6454 non-null   object
dtypes: float64(1), int64(1), object(3)
memory usage: 252.2+ KB

#### 5. Check For Duplicate Data and Drop Them

In [15]:
df.isnull().count()

year      6454
state     6454
month     6454
number    6454
date      6454
dtype: int64